nacos:
  config:
    server-addr: 172.31.16.237:8848
    namespace: dev
  discovery:
    server-addr: 172.31.16.237:8848
    namespace: dev
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.31.16.237:8848
        namespace: dev
server:
  port: 8082